### ISSUE TITLE
no live upstreams while connecting to upstream

### ISSUE THREAD

**Issue by BMWfan** [buchdag/multiarch-letsencrypt-nginx-proxy#5]
Hello,

i installed the 2 Container Version and made everything as described, but i get the following error message:

`2019/08/20 18:13:10 [error] 212#212: *26 no live upstreams while connecting to upstream, client: 86.175.42.181, server: container.mydomain.de, request: "GET / HTTP/2.0", upstream: "http://container.mydomain.de/", host: "container.mydomain.de"
`

The SSL signing worked as expected.

This are my settings in the container which i want to reach over a SSL signed Subdomain:

```yaml
version: "3"
services:
  container:
    image: container-image
    container_name: 'container'
    environment:
      TZ: 'Europe/Berlin'
      PGID: '1000'
      PUID: '1000'
      VIRTUAL_HOST: 'container'
      VIRTUAL_PORT: '6789'
      LETSENCRYPT_HOST: 'container.mydomain.de'
      LETSENCRYPT_EMAIL: 'suer@mydomain.de'
    ports:
      - "6789:6789"
    volumes:
      - /etc/container:/config
    restart: unless-stopped
    networks:
      - container
```

The Subomain Website shows me:
502 Bad Gateway
___________________
nginx/1.13.12

Is there any failure in my configuration?

Greetings

Daniel
